name: kubernetes-client-helper
version: 0.1.0.0
library:
  source-dirs: src
dependencies:
  - base >=4.7 && <5.0
  - kubernetes == 0.1.0.0
  - pem
  - x509
  - tls
  - x509-system
  - x509-store
  - data-default-class
  - connection
  - x509-validation
  - http-client
  - http-client-tls
  - microlens
  - bytestring
  - text
  - safe-exceptions



